### ISSUE TITLE
幾個建議

### ISSUE THREAD

**Issue by FongMi** [LZ9/MMSPlayer#2]
希望可以訪問到 mMediaPlayer
因為需要訂製 user-agent、隨時切換 Ratio

**Comment by LZ9** [comment]
我在MmsVideoView.Listener的监听器里增加了一个MediaPlayer创建成功的回调onMediaPlayerCreated，你可以在回调中获取MediaPlayer对象
请使用最新版本：implementation 'ink.lodz:mmsplayer:1.1.1'

**Comment by LZ9** [comment]
我在MmsVideoView.Listener的监听器里增加了一个MediaPlayer创建成功的回调，你可以在回调中获取MediaPlayer对象
请使用最新版本：implementation 'ink.lodz:mmsplayer:1.1.1'

**Comment by FongMi** [comment]
好的，謝謝。
