### ISSUE TITLE
有倍速吗

### ISSUE THREAD

**Issue by uaoan** [LZ9/MMSPlayer#3]
有播放倍速吗？

**Comment by LZ9** [comment]
我在ijk的代码里找了一圈，只有在IjkMediaPlayer的749行里有发现一个setSpeed()的方法看起来是和倍速比较相关的，但是调用了下似乎并不起作用。
看了下网上的文章，似乎是可以通过修改jni里的代码来实现，C这块我不大拿手，如果你刚兴趣可以自己尝试下，具体参考：https://www.cnblogs.com/renhui/p/6510872.html
