### ISSUE TITLE
請問你的 so 編譯環境是 ffmpeg 4 嗎

### ISSUE THREAD

**Issue by FongMi** [LZ9/MMSPlayer#4]

**Comment by FongMi** [comment]
請問可以即時切換 Surface 或 Texture 嗎

**Comment by LZ9** [comment]
1、我工程里的的so库是从哔哩哔的APK里面取出来的，并非是我自己编译的
2、之前确实没有考虑到要去动态切换RenderViewType，后续我会抽空补充一下并测试

**Comment by FongMi** [comment]
好的，感謝。
